### ISSUE TITLE
path not allowed to be mounted

### ISSUE THREAD

**Issue by hirani89** [BruskiCaleb/ES-Kibana-on-Docker#1]
Hi,

Thanks for the video and the compose file.

I am getting an error `path not allowed to be mounted`

i have edited the compose file to only use 1 instance of elastic search

```
version: "3.7"
services:
  es01:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: es01
      discovery.seed_hosts: es01
      cluster.initial_master_nodes: es01
      cluster.name: mycluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    depends_on:
      es01:
        condition: service_healthy
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://es01:9200"]'
volumes:
  es-data-es01:
```
